name: 'PR Description'
on:
    pull_request:
        types:
          - opened
          - edited
          - reopened

jobs:
    enforce:
        runs-on: ubuntu-20.04

        steps:
            - uses: derkinderfietsen/pr-description-enforcer@v1
              with:
                  repo-token: ${{ secrets.GH_TOKEN }}
